SamuelRnn/lazy-buy

prisma/index.js
index archive accesed by importing {} from "/prisma"
=> create(prisma/): reexport querys from client

pages/api/create/company.js, pages/api/create/user.js, prisma/schema.prisma
I've created the route 'api/create/user'. And also I've added an Enum PlanType, the name row to the Company Model and the relation between Company and Plan have changed
=> @dev/sojo506

components/Card.jsx, pages/404.jsx, pages/index.jsx
=> @dev/bravoezz

pages/_app.js, prisma/schema.prisma
config models optional fields and _app with provider
=> @dev/samuelrnn

pages/404.jsx
=> modify(pages/404): modify tag image

pages/SignUp.jsx
feat(pages/SignUp) : add styles
=> feat(pages/SignUp route): add styles

pages/api/create/product.js
=> add(api/create/product): route create product created

pages/api/get/product.js
=> add(api/create/product): route product created

package-lock.json, package.json
=> add(pakage): bcryptjs addded

pages/api/get/productid.js
/api/product modified
/api/productid created
=> create&mod(/api): adjusted get/product and created get/productid routes

pages/api/get/productid.js, pages/api/get/user.js, pages/api/get/userid.js
=> mod(/api): modified get/productid

pages/api/get/company.js, pages/api/get/companyid.js, pages/api/get/productid.js, pages/api/get/user.js, pages/api/get/userid.js
Replace .params for .query
Rename function name
=> mod(/api): modified /productid, get/user, get/userid routes

pages/login.jsx
=> fix(pages/login): login fixed

prisma/schema.prisma
=> fix(prisma): schema fixed

pages/api/auth/[...nextauth].js, prisma/schema.prisma
=> modify(prisma): getting back to the last schema

components/DashBoard/SideBar.jsx, pages/api/auth/signup/company.js, pages/signup.jsx, utils/validateForm.js
=> modify(SignUp) signup done 1/2

components/signCompany.jsx, pages/signup.jsx
=> modify(signup) components modified

pages/404.jsx
=> mod(pages/404) Translate to english

pages/faqs.jsx
Translate to english, center questioncircle, change colors
=> mod(pages/faqs) 

components/Elements/Devs.jsx
=> mod(components/Elements/Devs) add my github and linkedin

components/Elements_Layout/Footer.jsx
=> mod(components/Elements_Layout/Footer) Translate to english

pages/products/[slug].jsx
Translate to english, change button "back", delete colors and size.
=> mod(pages/products/slug) Translate to english, change button,delete colors and size

pages/order-detail.jsx
=> mod(pages/order-detail) mod

components/DashBoard/HomeHeader.jsx, styles/globals.css
=> @dev/agdelfino
